// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYMHyMk7c5rTojZuxD1eeZchOlZrWX90',
    appId: '1:738911688836:web:2fb23462d87007926c8ad1',
    messagingSenderId: '738911688836',
    projectId: 'madproject-f674c',
    authDomain: 'madproject-f674c.firebaseapp.com',
    storageBucket: 'madproject-f674c.firebasestorage.app',
    measurementId: 'G-BVQK4B4ZS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN15poALe7fgfIHfB3ka_QIr2XbG-Y-G0',
    appId: '1:738911688836:android:b70ffbd063a3c9ce6c8ad1',
    messagingSenderId: '738911688836',
    projectId: 'madproject-f674c',
    storageBucket: 'madproject-f674c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjRAQXsoFzZEDYhnq6qFipj3YgV8xGv5s',
    appId: '1:738911688836:ios:8e3016cda4555cd16c8ad1',
    messagingSenderId: '738911688836',
    projectId: 'madproject-f674c',
    storageBucket: 'madproject-f674c.firebasestorage.app',
    iosBundleId: 'com.zenva.madProject',
  );
}
